<?php
return array(
        'role_level' => [
                1 => 'Administrator',
                2 => 'Staff',
                3 => 'Editor',
        ],
        'Administrator' => 1,
        'Staff' => 2,
        'Editor' => 3,
        'Agent' => 4,
        'Developer' => 5,
        'User' => 6,
        'user_type' => [
                4 => 'Agent',
                5 => 'Developer',
                6 => 'User',
        ],
        'agent_type' => [
                1 => 'Property Agency',
                2 => 'Individual Agent',
                3 => 'Property Developer Company',
                4 => 'Renovation Company',
                5 => 'Transportation Company',
        ],
        'type_of_street' => [
                1 => 'Road',
                2 => 'On the inner road',
                3 => 'Inner lane',
        ],
        'partation_type' => [
                1 => 'Hall',
                2 => 'Partation',
        ],
        'area' => [
                1 => 'Square Feet',
                2 => 'Acre',
        ],
        'area_short' => [
                1 => 'SQ',
                2 => 'AC',
        ],
        'area_option' => [
                1 => 'Width x Length',
                2 => 'Area',
        ],
        'currency_code' => [
                'mmk' => 'MMK',
                'us' => 'US',
                'sg' => 'SG',
        ],
        'installment' => [
                1 => 'Yes',
                0 => 'No',
        ],
        'purchase_type' => [
                1 => 'Cash',
                2 => 'Cash + Bank',
                3 => 'Bank'
        ],
        'building_repairing' => [
                1 => 'Not Yet',
                2 => 'Half Finished',
                3 => 'Fully Finished'
        ],
        'preparation' => [
                1 => 'Not Yet',
                2 => 'Half Finished',
                3 => 'Fully Finished'
        ],
        'furnished_status' => [
                1 => 'Not Furnished',
                2 => 'Half Furnished',
                3 => 'Fully Furnished'
        ],
        'building_condition' => [
                1 => 'Living',
                2 => 'Currently Unoccupied',
                3 => 'New House'
        ],

        'fence_condition' => [
                1 => 'Yes',
                0 => 'No',
        ],
        'building_type' => [
                1 => 'Apartment',
                2 => 'Condominium',
        ],
        'broker' => [
                1 => 'Yes',
                0 => 'No',
        ],
        'land_type' => [
                1 => 'Garden Land',
                2 => 'Farm Land',
                3 => 'Kaing Kyun Land',
                4 => 'Other'
        ],
        'admin_usertype' => [
                1 => 'Administrator',
                2 => 'Staff',
                3 => 'Editor',
        ],
        'shop_type' => [
                1 => 'City Market Shop',
                2 => 'Shop',
                3 => 'Shop House'
        ],
        'industrial_type' => [
                1 => 'Only Industrial Land',
                2 => 'Warehouse And Building',
        ],
        'news_category' => [
                1 => 'RealEstate News',
                2 => 'RealEstate Knowledge',
                3 => 'RealEstate FaQ',
        ],
        'floor_level' => [
                1 => 'Penth House',
                2 => 'Ground Floor',
                3 => '1 Floor',
                4 => '2 Floor',
                5 => '3 Floor',
                6 => '4 Floor',
                7 => '5 Floor',
                8 => '6 Floor',
                9 => '7 Floor',
                10 => '8 Floor',
                11 => '9 Floor',
                12 => '10 Floor',
                13 => '11 Floor',
                14 => '12 Floor',
                15 => '13 Floor',
                16 => '14 Floor',
                17 => '15 Floor',
                18 => '16 Floor',
                19 => '17 Floor',
                20 => '18 Floor',
                21 => '19 Floor',
                22 => '20 Floor',
                23 => '21 Floor',
                24 => '22 Floor',
                25 => '23 Floor',
                26 => '26 Floor',
                27 => '27 Floor',

        ],
        'property_category' => [
                1 => 'House',
                2 => 'Land For House',
                3 => 'Apartment',
                4 => 'Office',
                5 => 'Land',
                6 => 'Shop',
                7 => 'Industrial Zone',
                8 => 'Condominium',
        ],
        'property_category_img' => [
                [
                        'id' => 1,
                        'title' => 'House',
                        'url' => 'storage/property_images/house.jpg',
                ],
                [
                        'id' => 2,
                        'title' => 'Land For House',
                        'url' => 'storage/property_images/land_house.jpg',
                ],
                [
                        'id' => 3,
                        'title' => 'Apartment',
                        'url' => 'storage/property_images/apartment.jpg',
                ],
                [
                        'id' => 4,
                        'title' => 'Office',
                        'url' => 'storage/property_images/office.jpg',
                ],
                [
                        'id' => 5,
                        'title' => 'Land',
                        'url' => 'storage/property_images/land.jpg',
                ],
                [
                        'id' => 6,
                        'title' => 'Shop',
                        'url' => 'storage/property_images/shop.jpg',
                ],
                [
                        'id' => 7,
                        'title' => 'Industrial Zone',
                        'url' => 'storage/property_images/industrial.jpg',
                ],
                [
                        'id' => 8,
                        'title' => 'Condo',
                        'url' => 'storage/property_images/condo.jpg',
                ],
        ],
        'developer_sale_type' => [
                1 => 'House',
                2 => 'Land',
                3 => 'Apartment',
                4 => 'Condo',
                5 => 'Villa',
                6 => 'Shop',
                7 => 'Office',
        ],
        'property_type' => [
                1 => 'Sale',
                2 => 'Rent',
        ],
        'minimum_month' => [
                1 => '1 Month',
                2 => '3 Months',
                3 => '6 Months',
                4 => '12 Months',
        ],
        'rent_pay_type' => [
                1 => 'Pay By Monthly',
                2 => 'Pay By Contract',
        ],
        'rent_payby_daily' => [
                1 => 'Available',
                2 => 'Unavailable',
        ],
        'publish_status' => [
                1 => 'Publish',
                0 => 'Pending',
        ],
        'recommend_status' => [
                1 => 'Recommend',
                0 => 'Normal',
        ],
        'hot_status' => [
                1 => 'Hot',
                0 => 'Normal',
        ],
        'slider_status' => [
                1 => 'Published',
                0 => 'Pending',
        ],
        'p_img_path' => 'storage/property_images/',
        'company_images' => 'storage/company_images/',
        'news_img_path' => 'storage/news/',
        'new_project_img_path' => 'storage/new_project/',
        'sliders_img_path' => 'storage/slider/',
        'bath_room' => [
                1 => '1',
                2 => '2',
                3 => '3',
                4 => '4',
                5 => '5',
                6 => '6',
                7 => '7',
                8 => '8',
                9 => '9',
                10 => '10',
        ],
        'bed_room' => [
                1 => '1',
                2 => '2',
                3 => '3',
                4 => '4',
                5 => '5',
                6 => '6',
                7 => '7',
                8 => '8',
                9 => '9',
                10 => '10',
        ],
        'unit_amenity' => [
                'refrigerator',
                'washing_machine',
                'mirowave',
                'gas_or_electric_stove',
                'air_conditioning',
                'tv',
                'cable_satellite',
                'internet_wifi',
                'water_heater',
                'security_cctv',
                'fire_alarm',
                'dinning_table',
                'bed',
                'sofa_chair',
                'private_swimming_pool',
        ],
        'building_amenity' => [
                'elevator',
                'garage',
                'fitness_center',
                'security',
                'swimming_pool',
                'spa_hot_tub',
                'playground',
                'garden',
                'carpark',
                'own_transformer',
                'disposal',
        ],
        'lot_feature' => [
                'cornet_lot',
                'garden',
                'lake',
                'mountain',
                'river',
                'pool',
                'sea',
                'city',
                'pagoda',
        ],
        'sort' => [
                'new',
                'old',
                'min',
                'max',
        ],
        'water_sys' => [
                1 => 'Yes',
                0 => 'No'
        ],
        'electricity_sys' => [
                1 => 'Yes',
                0 => 'No'
        ],
        'unauthorized' => 'Unauthorized',
        'fail_to_request' => 'Fail to request',
        
        // 'region' => [
        //         1 => 'Yangon Region',
        //         2 => 'Mandalay Region',
        //         3 => 'Bago Region',
        //         4 => 'Ayeyarwady Region',
        //         5 => 'Magway Region',
        //         6 => 'Sagaing Region',
        //         7 => 'Tanintharyi Region',
        //         8 => 'Shan State',
        //         9 => 'Kayin State',
        //         10 => 'Mon State',
        //         11 => 'Rakhine State',
        //         12 => 'Chin State',
        //         13 => 'Kachin State',
        //         14 => 'Kayah State',
        //         15 => 'Nay Pyi Taw',
        // ],
        // 'yangon' => [
        //         1 => 'Lanmadaw',
        //         2 => 'Latha',
        //         3 => 'Kyauktada',
        //         4 => 'Pabedan',
        //         5 => 'Pazundaung',
        //         6 => 'Ahlone',
        //         7 => 'Kyeemyindaing',
        //         8 => 'Sanchaung',
        //         9 => 'Bahan',
        //         10 => 'Botahtaung',
        //         11 => 'Mingalartaungnyunt',
        //         12 => 'Tamwe',
        //         13 => 'Yankin',
        //         14 => 'Dagon',
        //         15 => 'Dagon Myothit (East)',
        //         17 => 'Dagon Myothit (North)',
        //         18 => 'Dagon Myothit (South)',
        //         19 => 'Dagon Myothit (Seikkan)',
        //         20 => 'Kamaryut',
        //         21 => 'Insein',
        //         22 => 'Hlaing',
        //         23 => 'Hlaingtharya',
        //         24 => 'Mayangone',
        //         25 => 'Mingaladon',
        //         26 => 'North Okkalapa',
        //         27 => 'South Okkalapa',
        //         28 => 'Thingangyun',
        //         29 => 'Thaketa',
        //         30 => 'Thanlyin',
        //         31 => 'Dala',
        //         32 => 'Dawbon',
        //         33 => 'Hmawbi',
        //         34 => 'Hlegu',
        //         35 => 'Htantabin',
        //         36 => 'Kawhmu',
        //         37 => 'Kayan',
        //         38 => 'Kungyangon',
        //         39 => 'Shwepyithar',
        //         40 => 'Taikkyi',
        //         41 => 'Thongwa',
        //         42 => 'Twantay',
        //         43 => 'Kyauktan',
        //         44 => 'Seikgyikanaungto',
        //         45 => 'Palae Myothit',
        // ],
        // 'mandalay' => [
        //         1 => 'Aung Myay Thar Zan',
        //         2 => 'Chan Aye Thar Zan',
        //         3 => 'Mahar Aung Myay',
        //         4 => 'Chan Mya Thar Si',
        //         5 => 'Pyi Gyi Tan Kon',
        //         6 => 'Amarapura',
        //         7 => 'Pa Thein Gyi',
        //         8 => 'Pyin Oo Lwin',
        //         9 => 'Madaya',
        //         10 => 'Singu',
        //         11 => 'Thabeikkyin',
        //         12 => 'Mogok',
        //         13 => 'Kyaukpadaung',
        //         14 => 'Kyaukse',
        //         15 => 'Sintgaing',
        //         16 => 'Myittha',
        //         17 => 'Tada-U',
        //         18 => 'Myingyan',
        //         19 => 'Thaungtha',
        //         20 => 'Natogyi',
        //         21 => 'Nyaung-U',
        //         22 => 'Meiktila',
        //         23 => 'Mahlaing',
        //         24 => 'Thazi',
        //         25 => 'Wundwin',
        //         26 => 'Pyawbwe',
        //         27 => 'Yamethin',
        // ],
        // 'naypyitaw' => [
        //         1 => 'Pyinmana',
        //         2 => 'Tatkon',
        //         3 => 'Lewe',
        //         4 => 'Dekkhinathiri',
        //         5 => 'Ottarathiri',
        //         6 => 'Pobbathiri',
        //         7 => 'Zabuthiri',
        //         8 => 'Zeyathiri',
        // ],
        // 'bago' => [
        //         1 => 'Bago',
        //         2 => 'Daik-U',
        //         3 => 'Kawa',
        //         4 => 'Thanatpin',
        //         5 => 'Waw',
        //         6 => 'Nyaunglebin',
        //         7 => 'Shwegyin',
        //         8 => 'Pyay',
        //         9 => 'Paukkaung',
        //         10 => 'Thegon',
        //         11 => 'Shwedaung',
        //         12 => 'Padaung',
        //         13 => 'Paungde',
        //         14 => 'Nattalin',
        //         15 => 'Zigon',
        //         16 => 'Tharrawaddy',
        //         17 => 'Gyobingauk',
        //         18 => 'Letpadan',
        //         19 => 'Minhla',
        //         20 => 'Monyo',
        //         21 => 'Okpho',
        //         22 => 'Taungoo',
        //         23 => 'Oktwin',
        //         24 => 'Tantabin',
        //         25 => 'Yedashe',
        //         26 => 'Pyu',
        //         27 => 'Kyauktaga',
        //         28 => 'Kyaukkyi',
        //         29 => 'Hpa Yar Gyi',
        // ],
        // 'ayarwaddy' => [
        //         1 => 'Bogale',
        //         2 => 'Danubyu',
        //         3 => 'Einme',
        //         4 => 'Hinthada',
        //         5 => 'Ingapu',
        //         6 => 'Kangyidaunt',
        //         7 => 'Kyaiklat',
        //         8 => 'Kyangin',
        //         9 => 'Kyaunggon',
        //         10 => 'Kyonpyaw',
        //         11 => 'Labutta',
        //         12 => 'Lemyethna',
        //         13 => 'Maubin',
        //         14 => 'Mawlamyinegyun',
        //         15 => 'Myanaung',
        //         16 => 'Myaungmya',
        //         17 => 'Ngapudaw',
        //         18 => 'Nyaungdon',
        //         19 => 'Pantanaw',
        //         20 => 'Pathein',
        //         21 => 'Pyapon',
        //         22 => 'Thabaung',
        //         23 => 'Wakema',
        //         24 => 'Yegyi',
        //         25 => 'Zalun',
        // ],
        // 'magway' => [
        //         1 => 'Aunglan',
        //         2 => 'Chauk',
        //         3 => 'Gangaw',
        //         4 => 'Kamma',
        //         5 => 'Magway',
        //         6 => 'Minbu',
        //         7 => 'Mindon',
        //         8 => 'Minhla',
        //         9 => 'Myaing',
        //         10 => 'Myothit',
        //         11 => 'Natmauk',
        //         12 => 'Ngape',
        //         13 => 'Pakokku',
        //         14 => 'Pauk',
        //         15 => 'Pwintbyu',
        //         16 => 'Salin',
        //         17 => 'Saw',
        //         18 => 'Seikphyu',
        //         19 => 'Sidoktaya',
        //         20 => 'Sinbaungwe',
        //         21 => 'Taungdwingyi',
        //         22 => 'Thayet',
        //         23 => 'Tilin',
        //         24 => 'Yenangyaung',
        //         25 => 'Yesagyo',
        // ],
        // 'saging' => [
        //         1 => 'Sagaing',
        //         2 => 'Monywa',
        //         3 => 'Shwebo',
        //         4 => 'Tabayin',
        //         5 => 'Katha',
        //         6 => 'Ayadaw',
        //         7 => 'Banmauk',
        //         8 => 'Budalin',
        //         9 => 'Chaung-U',
        //         10 => 'Hkamti',
        //         11 => 'Homalin',
        //         12 => 'Indaw',
        //         13 => 'Kale',
        //         14 => 'Kalewa',
        //         15 => 'kanbalu',
        //         16 => 'Kani',
        //         17 => 'Kawlin',
        //         18 => 'Khin-U',
        //         19 => 'Kyunhla',
        //         20 => 'Lahe',
        //         21 => 'Mawlaik',
        //         22 => 'Mingin',
        //         23 => 'Myaung',
        //         24 => 'Myinmu',
        //         25 => 'Nanyun',
        //         26 => 'Pale',
        //         27 => 'Paungbyin',
        //         28 => 'Pinlebu',
        //         29 => 'Salingyi',
        //         30 => 'Tamu',
        //         31 => 'Taze',
        //         32 => 'Tigyaing',
        //         33 => 'Wetlet',
        //         34 => 'Wuntho',
        //         35 => 'Ye-U',
        //         36 => 'Yinmabin',
        // ],
        // 'tanintharyi' => [
        //         1 => 'Dawei',
        //         2 => 'Kawthoung',
        //         3 => 'Myeik',
        //         4 => 'Bokpyin',
        //         5 => 'Kyunsu',
        //         6 => 'Palaw',
        //         7 => 'Tanintharyi',
        //         8 => 'Thayetchaung',
        //         9 => 'Yebyu',
        // ],
        // 'shan' => [
        //         1 => 'Taunggyi',
        //         2 => 'Kalaw',
        //         3 => 'Aung Ban',
        //         4 => 'Kengtung',
        //         5 => 'Tachileik',
        //         6 => 'Hsipaw',
        //         7 => 'Kyuakme',
        //         8 => 'Lashio',
        //         9 => 'Muse',
        //         10 => 'Nawnghkio',
        //         11 => 'Hopong',
        //         12 => 'Loilen',
        //         13 => 'Nyaungshwe',
        //         14 => 'Pindaya',
        //         15 => 'Pinlaung',
        //         16 => 'Matman',
        //         17 => 'Monghpyak',
        //         18 => 'Monghsat',
        //         19 => 'Mongkhet',
        //         20 => 'Mongla',
        //         21 => 'Mongping',
        //         22 => 'Mongton',
        //         23 => 'Mongyang',
        //         24 => 'Mongyawng',
        //         25 => 'Hopang',
        //         26 => 'Hseni',
        //         27 => 'Konkyan',
        //         28 => 'Kunlong',
        //         29 => 'Kutkai',
        //         30 => 'Laukkaing',
        //         31 => 'Mabein',
        //         32 => 'Mongmao',
        //         33 => 'Mongmit',
        //         34 => 'Mongyai',
        //         35 => 'Namhsan',
        //         36 => 'Namtu',
        //         37 => 'Nanhkan',
        //         38 => 'Pangsang',
        //         39 => 'Pangwaun',
        //         40 => 'Tangyan',
        //         41 => 'Hsihseng',
        //         42 => 'Kunhing',
        //         43 => 'Kyethi',
        //         44 => 'Laihka',
        //         45 => 'Langkho',
        //         46 => 'Lawksawk',
        //         47 => 'Mawkmai',
        //         48 => 'Monghsu',
        //         49 => 'Mongkaung',
        //         50 => 'Mongnai',
        //         51 => 'Mongpan',
        //         52 => 'Nansang',
        //         53 => 'Pekon',
        //         54 => 'Ywangan',
        // ],
        // 'chin' => [
        //         1 => 'Falam',
        //         2 => 'Hakha',
        //         3 => 'Htantlang',
        //         4 => 'Kanpetlet',
        //         5 => 'Madupi',
        //         6 => 'Mindat',
        //         7 => 'Paletwa',
        //         8 => 'Tiddim',
        //         9 => 'Tonzang',
        // ],
        // 'kachin' => [
        //         1 => 'Bhamo',
        //         2 => 'Chipwi',
        //         3 => 'Hpakan',
        //         4 => 'Injangyang',
        //         5 => 'Kawnglanghpu',
        //         6 => 'Machanbaw',
        //         7 => 'Mansi',
        //         8 => 'Mogaung',
        //         9 => 'Mohnyin',
        //         10 => 'Momauk',
        //         11 => 'Myitkyina',
        //         12 => 'Nogmung',
        //         13 => 'Puta-O',
        //         14 => 'Shwegu',
        //         15 => 'Sumprabum',
        //         16 => 'Tanai',
        //         17 => 'Tsawlaw',
        //         18 => 'Waingmaw',
        // ],
        // 'kayah' => [
        //         'Bawlakhe',
        //         'Demoso',
        //         'Hpasawng',
        //         'Hpruso',
        //         'Loikaw',
        //         'Mese',
        //         'Shadaw',
        // ],
        // 'kayin' => [
        //         'Hlaingbwe',
        //         'Hpa-An',
        //         'Hpapun',
        //         'Kawkareik',
        //         'Kyain Seikgyi',
        //         'Myawaddy',
        //         'Thandaung',
        // ],
        // 'mon' => [
        //         'Bilin',
        //         'Chaungzon',
        //         'Kyaikmaraw',
        //         'Kyaikto',
        //         'Kyaukpyu',
        //         'Mawlamyine',
        //         'Mudon',
        //         'Paung',
        //         'Thanbyuzayat',
        //         'Thaton',
        //         'Ye',
        // ],
        // 'rakhine' => [
        //         'Ann',
        //         'Buthidaung',
        //         'Gwa',
        //         'Kyauktaw',
        //         'Maungdaw',
        //         'Minbya',
        //         'Mrauk-U',
        //         'Munaung',
        //         'Myebon',
        //         'Pauktaw',
        //         'Ponnagyun',
        //         'Ramree',
        //         'Rathedaung',
        //         'Sittwe',
        //         'Thandwe',
        //         'Toungup',
        // ]

);
